OPTION_LIST = ["Home",
               "View Doctors",
               "View Patients",
               "View Medicines",
               "View Insurances",
               "Find Doctor By ID",
               "Create Doctor",
               "Update Doctor",
               "Delete Doctor By ID",
               "Find Doctor by Department ID",
               "Find Departments by Doctor ID",
               "Find Patient By ID",
               "Create Patient",
               "Update Patient",
               "Delete Patient By ID",
               "Find Patients By Insurance ID",
               "Find Medicine By ID",
               "Create Medicine",
               "Update Medicine",
               "Delete Medicine By ID",
               "Find Insurance By ID",
               "Create Insurance",
               "Update Insurance",
               "Delete Insurance By ID",
               "Find Insurances By Patient ID",
               "Find Insurances By Bill ID",
               "Find Bills By Insurance ID"]
