OPTION_LIST = ["Home",
               " -------- ",
               "View Doctors",
               "Find Doctor By ID",
               "Create Doctor",
               "Update Doctor",
               "Delete Doctor By ID",
               "Find Doctor by Department ID",
               "Find Departments by Doctor ID",
               "Find Doctors by Patient ID",
               " -------- ",

               "View Patients",
               "Find Patient By ID",
               "Create Patient",
               "Update Patient",
               "Delete Patient By ID",
               "Find Patients By Insurance ID",
               "Find Patients By Doctor ID",
               " -------- ",

               "View Medicines",
               "Find Medicine By ID",
               "Create Medicine",
               "Update Medicine",
               "Delete Medicine By ID",
               " -------- ",

               "View Insurances",
               "Find Insurance By ID",
               "Create Insurance",
               "Update Insurance",
               "Delete Insurance By ID",
               "Find Insurances By Patient ID",
               "Find Insurances By Bill ID",
               " -------- ",

               "View Bills",
               "Find Bill By ID",
               "Create Bill",
               "Update Bill",
               "Delete Bill By ID",
               "Find Bills By Insurance ID",
               " -------- ",

               "View Lab Fees",
               "Find Lab Fees By Bill ID",
               "Create Lab Fees",
               "Update Lab Fees",
               "Delete Lab Fees By ID",
               ]
